# Generated by Django 4.2.6 on 2024-05-28 22:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
