# Generated by Django 4.2.6 on 2024-04-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_variation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variation",
            name="variation_category",
            field=models.CharField(choices=[("color", "color")], max_length=100),
        ),
    ]
